# Generated by Django 3.2.9 on 2022-02-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=20)),
                ('amount', models.BigIntegerField()),
                ('amount_paid', models.IntegerField()),
                ('amount_due', models.IntegerField()),
                ('currency', models.CharField(max_length=20)),
                ('receipt', models.CharField(max_length=25)),
                ('status', models.CharField(max_length=20)),
                ('attempts', models.IntegerField()),
                ('created_at', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('razorpay_payment_id', models.CharField(max_length=23)),
                ('razorpay_order_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('razorpay_signature', models.CharField(max_length=70)),
            ],
        ),
    ]
